name: "Infrastructure Creation"
on:
    push:
      branches:
        - master
  
jobs:
    Deploy_Dev:
        uses: rupeshkanth218/tf_cloud_aws_actions/.github/workflows/tf_apply.yml@main
        with :
            path: tf_infra
            region: ${{ vars.AWS_REGION}}
            repository: pythonapp
            
        secrets:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
            access_token: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret_access_token: ${{ secrets.AWS_SECRET_ACCESS_KEY }}