name: "Infrastructure Creation"
on:
    push:
      branches:
        - master
  
jobs:
    Deploy_Dev:
        uses: VarunMayanger/aws-Infra-and-app/.github/workflows/tf_apply.yml@master
        with :
            path: terraform/workspace/nike
            region: ${{ vars.AWS_REGION}}
            repository: aws_infra
            
        secrets:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
            access_token: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret_access_token: ${{ secrets.AWS_SECRET_ACCESS_KEY }}